settings:
  id: sample
  site_url: https://sample.donohoe.info
  output_dir: web
  descriptions: descriptions.txt

bases:
  sample: sample/source

albums:
  - slug: antarctica
    name: Antarctica
    base: sample
    source: antarctica
    cover: neko_harbour_01.jpg
    manual_sort_order: true
